package littler.datetime;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;

import littler.exception.LittleRException;

/**
 * Utility class that handles parsing, formatting, and converting date and time strings
 * to and from {@link ParsedDateTime} representations.
 */
public final class StringDateTimeConverter {

    private static final DateTimeFormatter DISPLAY_DATE =
        DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter DISPLAY_TIME =
        DateTimeFormatter.ofPattern("HH:mm");

    // Formats that include a time component (HHmm, 24-hour)
    private static final List<DateTimeFormatter> DATE_TIME_FORMATS = List.of(
        DateTimeFormatter.ofPattern("d-M-yyyy HHmm"),
        DateTimeFormatter.ofPattern("yyyy-M-d HHmm")
    );

    // Date-only formats; result will have no time component
    private static final List<DateTimeFormatter> DATE_ONLY_FORMATS = List.of(
        DateTimeFormatter.ofPattern("d-M-yyyy"),
        DateTimeFormatter.ofPattern("yyyy-M-d")
    );

    private StringDateTimeConverter() {}

    /**
     * Encodes a ParsedDateTime object into a deterministic format for storage.
     * Format example: "2019-12-02|18:00" or "2019-12-02|NONE" if no time was specified.
     *
     * @param dateTime the ParsedDateTime object to encode
     * @return the formatted storage string
     */
    public static String toStorageString(ParsedDateTime dateTime) {
        String dateStr = dateTime.getDate().format(DateTimeFormatter.ISO_LOCAL_DATE);
        String timeStr = dateTime.hasTime()
            ? dateTime.getTime().format(DateTimeFormatter.ISO_LOCAL_TIME)
            : "NONE";
        return dateStr + "|" + timeStr;
    }

    /**
     * Decodes a storage string generated by {@link #toStorageString(ParsedDateTime)} into a ParsedDateTime.
     *
     * @param stored the formatted date/time string read from file storage
     * @return the reconstructed ParsedDateTime object
     * @throws LittleRException if the stored string format is invalid or corrupted
     */
    public static ParsedDateTime fromStorageString(String stored) throws LittleRException {
        String[] parts = stored.split("\\|");
        if (parts.length != 2) {
            throw new LittleRException("Corrupted stored date: " + stored);
        }
        try {
            LocalDate date = LocalDate.parse(parts[0]);
            LocalTime time = parts[1].equals("NONE") ? null : LocalTime.parse(parts[1]);
            return new ParsedDateTime(date, time);
        } catch (DateTimeParseException e) {
            throw new LittleRException("Corrupted stored date: " + stored);
        }
    }

    /**
     * Parses a raw user input date/time string against all accepted patterns.
     *
     * @param input the user input date string to parse
     * @return a ParsedDateTime object containing the parsed date and optional time
     * @throws LittleRException if the input string does not match any accepted date/time format
     */
    public static ParsedDateTime parse(String input) throws LittleRException {
        String trimmed = input.trim();

        for (DateTimeFormatter format : DATE_TIME_FORMATS) {
            try {
                LocalDateTime dateTime = LocalDateTime.parse(trimmed, format);
                return new ParsedDateTime(dateTime.toLocalDate(), dateTime.toLocalTime());
            } catch (DateTimeParseException ignored) {
                // try next format
            }
        }

        for (DateTimeFormatter format : DATE_ONLY_FORMATS) {
            try {
                LocalDate date = LocalDate.parse(trimmed, format);
                return new ParsedDateTime(date, null);
            } catch (DateTimeParseException ignored) {
                // try next format
            }
        }

        throw new LittleRException(
            "Invalid date format: '" + input + "'. Accepted formats: "
            + "d-M-yyyy, or yyyy-M-d, each optionally followed by a time as HHmm "
            + "(e.g. 2-12-2019 1800). Time is omitted from output if not provided.");
    }

    /**
     * Formats a ParsedDateTime object for user-facing display.
     *
     * @param dateTime the ParsedDateTime object to format
     * @return the formatted display string (e.g. "2019-12-02" or "2019-12-02 18:00")
     */
    public static String format(ParsedDateTime dateTime) {
        String display = dateTime.getDate().format(DISPLAY_DATE);
        if (dateTime.hasTime()) {
            display += " " + dateTime.getTime().format(DISPLAY_TIME);
        }
        return display;
    }

    /**
     * Formats a standard LocalDate for display purposes using the default date pattern.
     *
     * @param date the LocalDate object to format
     * @return the formatted date string
     */
    public static String formatDate(LocalDate date) {
        return date.format(DISPLAY_DATE);
    }

    /**
     * Encapsulates a LocalDate object alongside an optional LocalTime component.
     */
    public static final class ParsedDateTime {
        private final LocalDate date;
        private final LocalTime time; // null means no time was specified

        /**
         * Constructs a ParsedDateTime instance with a required date and optional time component.
         *
         * @param date the date component
         * @param time the optional time component (may be null)
         */
        public ParsedDateTime(LocalDate date, LocalTime time) {
            this.date = date;
            this.time = time;
        }

        /**
         * Compares the date component of this object with another ParsedDateTime instance.
         *
         * @param other the target ParsedDateTime object to compare against
         * @return -1 if this date is earlier, 0 if equal, or 1 if later
         */
        public int compareDate(ParsedDateTime other) {
            if (this.date.isBefore(other.date)) {
                return -1;
            } else if (this.date.isAfter(other.date)) {
                return 1;
            } else {
                return 0;
            }
        }

        /**
         * Compares the time component of this object with another ParsedDateTime instance.
         * If either object lacks a time component, they are treated as equal.
         *
         * @param other the target ParsedDateTime object to compare against
         * @return -1 if this time is earlier, 0 if equal (or if either time is null), or 1 if later
         */
        public int compareTime(ParsedDateTime other) {
            if (this.time == null || other.time == null) {
                return 0; // Assume equal if either has no time
            }
            if (this.time.isBefore(other.time)) {
                return -1;
            } else if (this.time.isAfter(other.time)) {
                return 1;
            } else {
                return 0;
            }
        }

        /**
         * Returns the date component of this object.
         *
         * @return the LocalDate instance
         */
        private LocalDate getDate() {
            return date;
        }

        /**
         * Returns the optional time component of this object.
         * @return the LocalTime instance, or null if no time was set
         */
        private LocalTime getTime() {
            return time;
        }

        /**
         * Checks if this instance has an explicit time component set.
         * @return true if a time component is present; false otherwise
         */
        public boolean hasTime() {
            return time != null;
        }

        /**
         * Returns a string representation of this date/time formatted for display.
         *
         * @return the formatted date/time string
         */
        @Override
        public String toString() {
            return format(this);
        }
    }
}
